### ISSUE TITLE
Support aarch64(arm64), manylinux2010 and manylinux2014

### ISSUE THREAD

**Issue by SuperSandro2000** [parkoview/wheel2deb#2]
Can you add support for aarch64 (arm64), manylinux2010 and manylinux2014 wheels?

I need to have support for all three for to use this for my personal projects.

A few python packet that compiles to manylinux2010 on Debian based Linux are: Levenshtein, uvloop, coincurve and cryptography.

**Comment by fyhertz** [comment]
Hi,
https://github.com/parkoview/wheel2deb/commit/82a1c9d39118c8bc39063cc203e19c8611bd3573 should fix that. Can you tell if it does the trick for you so that I can close the issue?

**Comment by SuperSandro2000** [comment]
I don't have a good test case right now but it should probably do it.
